language: python
dist: xenial
python:
  - "3.7"
  - "3.6"
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  nosetests --with-coverage --cover-package=rumrunner
after_success:
  coveralls
